[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Force esbuild to use correct platform
  NPM_FLAGS = "--include=optional"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
