version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-urban_commute}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/urban_commute
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000,http://127.0.0.1:3000
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - TRAFFIC_API_KEY=${TRAFFIC_API_KEY}
      - KC_METRO_GTFS_URL=${KC_METRO_GTFS_URL:-https://kingcounty.gov/~/media/depts/metro/schedules/gtfs/current-feed.zip}
      - KC_METRO_GTFS_RT_URL=${KC_METRO_GTFS_RT_URL:-https://api.pugetsound.onebusaway.org/api/where}
    command: >
      bash -c "python -m app.db.init_db &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api  # Use localhost for browser

volumes:
  postgres_data: